### PR TITLE
A couple of things that didn't compile after the last commits to master

### PR DESCRIPTION
**Pull request by peterhull90**
Please see the individual commits for details.

### CODE REVIEW

**Comment by OnlineCop** [comment]
Odd; they were compiling for me, after multiple "clean project and recompile" passes. Guess I can't always trust my compiler. :-D

**Comment by peterhull90** [comment]
I've got `KQ_CHEATS` defined which maybe you haven't (hence the first diff) and I am using Lua 5.3 which may account for the other (also I'm on Visual Studio2015, how about you?)

**Comment by OnlineCop** [comment]
I may have left `KQ_CHEATS` off during the compiles. And all my testing is through an ArchLinux VM, using NetBeans as my IDE. I haven't been able to figure out how to compile and run correctly on Visual Studio, so if you know the steps to get all the packages to compile (Allegro 4, Lua 5, Dumb, and I think there was something else but I forget), I'm sure that any other Visual Studio users out there (myself included) would benefit.

**Comment by uncleshelby** [comment]
Even though I'm just using Vim and compiling manually, I'd love to know how to get it to compile in VS.

**Comment by peterhull90** [comment]
I've nearly got that sorted out, it required a few tweaks to the CMake file. Basically I've compiled a package of the dependencies, Allegro, DUMB, Lua in a single directory that you can drop into your KQ directory, then cmake will find and use it when it creates your Visual Studio solution.

It's nearly ready apart from the fact that the linker won't link libraries compiled under release mode with the main exe compiled under debug mode. Which I find amazing! It's something C++ specific but definitely a bit weird...

**Pull request merged**
