### PR TITLE
Support for compilation with new versions of g++

### PR DESCRIPTION
**Pull request by nkutya**
The commit that added support for older versions of g++ broke compatibility with new versions. This should fix it.

### CODE REVIEW

**Comment by nkutya** [comment]
Like this?

**Comment by uncleshelby** [comment]
It turns out that the `CXX_STANDARD` property is a feature new to CMake 3.1, see the [release notes](https://cmake.org/cmake/help/v3.1/release/3.1.0.html#properties). My installation of Linux Mint 17.2 installs CMake 2.8.12.2. Now, if we don't want to support anything lower than 3.0 (which was last released in September 2014), that's fine with me. I installed CMake 3.4.3 without any trouble, and it built fine with `CXX_STANDARD`.

If we drop support for 3.0 and lower, we should set `cmake_minimum_required(VERSION 3.1)`.

**Comment by uncleshelby** [comment]
I'm gonna go ahead and merge this request. @peterhull90 if you think we should downgrade to C++11, that sounds good. It'll be an easy change too.

**Comment by OnlineCop** [comment]
As long as it continues to compile on whatever platform we use, I'm fine with it. Do we need to upgrade all our CMake versions to 3.1 and later?

**Comment by uncleshelby** [comment]
Yeah, 3.1 or later. If you think we should continue support for older versions, I can start re-writing the other way I had it (a little more carefully this time).

**Comment by OnlineCop** [comment]
Nope. Without a good reason to use old libraries, old code, or old settings, I say we try to keep it as up-to-date as possible. It should make porting it to SDL that much easier.

**Comment by peterhull90** [comment]
Agreed. It seems reasonable for the developers to keep themselves relatively up-to-date. If it started requiring the *end users* to have the very latest kernel or install non-default stuff that might be a problem.

**Pull request merged**
