### PR TITLE
Reinstate doom and death spells

### LINKED ISSUE #109: Death and Doom spells don't work
They don't work when the player casts them and don't seem to do anything when the npc's casts them as well.

### PR DESCRIPTION
**Pull request by pedro-w**
@z9484 I believe this allows Doom to hit an enemy, I am not sure exactly where enemies might use it against us so could not test.
Fixes #109

### CODE REVIEW

**Comment by z9484** [comment]
Not sure if its just a weird merge issue but I had to change this to get it to compile
"-"        for (fighter_index = start_fighter_index; fighter_index < start_fighter_index + num_fighters; fighter_index++)
"+"        for (fighter_index = start_fighter_index; fighter_index < start_fighter_index + NUM_FIGHTERS; fighter_index++)

Hmm it works great for when the players use it but I got some weird behavior when the enemies use it. DoomToad and DeathRose use death and doom -> zone 90, forest on Malkaron's island x170 y108.  I wonder if it was because I had cheats on.

**Comment by OnlineCop** [comment]
Actually, that may be related to what I'm seeing in #124.

I definitely see a few of the stats being passed around with 1-based values and then used in functions that expect them to be 0-based (and vice-versa), which is probably what's throwing things off.

**Comment by OnlineCop** [comment]
For the last week and a half, I have started -- no exaggeration -- 5 complete "scrap and restart" refactors all related to this.

I think I've been luckiest so far in changing everything to 0-based, so instead of `0` indicating that there's no elemental effect, it uses `16` (or `eResistance::R_TOTAL_RES`) and then there's no need to remember which ones (I'm looking at you, `elem` and `welem`) need to be modified before passing into the functions that use them with the `res[]` array.

**Comment by pedro-w** [comment]
> Not sure if its just a weird merge issue but I had to change this to get it to compile 

Should be `end_fighter_index` - see the rest of the file. The name is wrong because it's used as a count rather than an index. I originally changed it everywhere to `num_fighters` then reverted that part of the PR in the interests of focus, but I missed that one, sorry.

**Comment by pedro-w** [comment]
Aiee I didn't want to merge this. Reverting.

edit: OK I didn't merge it in the first place. What's going on, Github?

**Review by OnlineCop — APPROVED** [review]

**Pull request merged**
