### PR TITLE
s_item items[] and s_spell magic[] changes

### PR DESCRIPTION
**Pull request by OnlineCop**
## Changes Magic Numbers to `enum` Values

This builds off of #141 to address issues in #124.

- It's late and I've got to do other things; I'll come back later and fill in all of the details on this commit in a bit.
- I believe I still need to do a similar thing to **allstat.mon**, but since that is using raw data (integers) and has no concept of compiling to an `enum`, that may be a bit more time-consuming.
- I have strongly considered moving the values from **allstat.mon** into code, like was done here in **res.cpp**. Then we could use enums to quickly eyeball the values and tell when things are 0- or 1-based.

This PR may require a lot of changes to the values, so feel free to critique it heavily.
- I'm hoping the parent PR that this is based on top of will have far fewer changes required, so it won't take as many rebases.

### CODE REVIEW

**Comment by OnlineCop** [comment]
## NOTE

This looks like it's showing the WHOLE commit history, from [9f4d599](https://github.com/OnlineCop/kq-fork/pull/142/commits/9f4d59956fe83ed94ee9dc7b16078404e2cc9111) to [a7a04ac](https://github.com/OnlineCop/kq-fork/pull/142/commits/a7a04ace1473cee8b4439d19b1aa37040c912867).

*You don't need to review any of those!**

Just the last one: [afe99f9](https://github.com/OnlineCop/kq-fork/pull/142/commits/afe99f9d7b4e2d0b657fdeb1955c8ba5bffeb5bb) (or whatever "`res.cpp: Fill out s_item[] and s_spell[]`" and its descendants become).

**Comment by pedro-w** [comment]
Is this ready to go in now, @OnlineCop ? Can you see if rebasing against `road_to_1.0` will get rid of all those extra historical commits, they make me nervous!

**Comment by pedro-w** [comment]
I tried rebasing with
```
git checkout upstream/dev/onlinecop/124_eResistance_0_based
git rebase upstream/road_to_1.0
```
it worked, the "res.cpp: Fill out s_item[] and s_spell[]" commit was the only one left, sitting on top of "upstream/road_to_1.0"

**Comment by OnlineCop** [comment]
Alright; pushed.

The values are almost entirely the same as before (if you had been going through the values previously), but with the names `eTarget::TGT_NONE`, `eResitance::R_NONE`, and `eEquipment::EQP_NONE` instead of the `MAX_*` or `TOTAL_*` names.

**Comment by pedro-w** [comment]
As far as I can tell this is OK, obviously there's no way to be 100% sure!

**Pull request merged**
