### PR TITLE
Bugfixes for music player

### PR DESCRIPTION
**Pull request by pedro-w**
1. ~~Don't attempt to change volume if music was never initialized~~ (this was dealt with in a previous PR)
2. Make sure to set the volume (as specified in the config file)
   when sound/music is initialized
3. When loading a game, set volume before the initial fade-in
4. Set the volume correctly when changing music volume on the
   config screen
5. Remove duplicate code

### CODE REVIEW

**Comment by OnlineCop** [comment]
I am unable to test that this works, as audio still does not work for me, but I see no issues with the code changes.

**Comment by pedro-w** [comment]
> as audio still does not work for me,

Just to clarify - you have no audio at all or just no music?
If you do `vcpkg search sdl2-mixer` do you see any "features" relating to libmodplug that aren't installed (see [here](https://vcpkg.io/en/docs/users/selecting-library-features.html))

**Comment by OnlineCop** [comment]
No audio at all. Going into the Configure screen and trying to enable sounds shows "...please wait..." briefly at the bottom, but the music/sound options do not become available. No sounds/music while playing the game either.

```bash
$ vcpkg search sdl2-mixer
sdl2-mixer               2.0.4#16         Multi-channel audio mixer library for SDL.
sdl2-mixer[dynamic-load]                  Load plugins with dynamic call.
sdl2-mixer[fluidsynth]                    Support for FluidSynth MIDI/SF2 audio format.
sdl2-mixer[libflac]                       Support for FLAC audio format.
sdl2-mixer[libmodplug]                    Support for MOD audio format.
sdl2-mixer[libvorbis]                     Support for OGG Vorbis audio format.
sdl2-mixer[mpg123]                        Support for MP3 audio format.
sdl2-mixer[nativemidi]                    Support for MIDI audio format on Windows and macOS.
sdl2-mixer[opusfile]                      Support for Opus audio format.

$ vcpkg list
libmodplug:x64-windows                             0.8.9.0#10       The ModPlug mod file playing library.
libpng:x64-windows                                 1.6.37#17        libpng is a library implementing an interface fo...
lua:x64-windows                                    5.4.4#2          A powerful, fast, lightweight, embeddable script...
sdl2-mixer:x64-windows                             2.0.4#16         Multi-channel audio mixer library for SDL.
sdl2-mixer[libmodplug]:x64-windows                                  Support for MOD audio format.
sdl2-mixer[nativemidi]:x64-windows                                  Support for MIDI audio format on Windows and macOS.
sdl2:x64-windows                                   2.0.22#1         Simple DirectMedia Layer is a cross-platform dev...
tinyxml2:x64-windows                               9.0.0#1          A simple, small, efficient, C++ XML parser
vcpkg-cmake-config:x64-windows                     2022-02-06#1
vcpkg-cmake:x64-windows                            2022-05-10#1
vcpkg-tool-meson:x64-windows                       0.62.1           Meson build system
zlib:x64-windows                                   1.2.12#1         A compression library
```

**Comment by OnlineCop** [comment]
Update: I removed the entire `vcpkg/` directory and reinstalled it, this time specifying the sdl2-mixer features at install time, instead of adding it after the fact:
```bash
$ vcpkg install --triplet x64-windows libpng lua sdl2 sdl2-mixer[libmodplug,nativemidi] tinyxml2 zlib
  ...

$ vcpkg list
libmodplug:x64-windows                             0.8.9.0#10       The ModPlug mod file playing library.
libpng:x64-windows                                 1.6.37#18        libpng is a library implementing an interface fo...
lua:x64-windows                                    5.4.4#2          A powerful, fast, lightweight, embeddable script...
sdl2-mixer:x64-windows                             2.0.4#16         Multi-channel audio mixer library for SDL.
sdl2-mixer[libmodplug]:x64-windows                                  Support for MOD audio format.
sdl2-mixer[nativemidi]:x64-windows                                  Support for MIDI audio format on Windows and macOS.
sdl2:x64-windows                                   2.0.22#1         Simple DirectMedia Layer is a cross-platform dev...
tinyxml2:x64-windows                               9.0.0#1          A simple, small, efficient, C++ XML parser
vcpkg-cmake-config:x64-windows                     2022-02-06#1
vcpkg-cmake:x64-windows                            2022-06-07
zlib:x64-windows                                   1.2.12#1         A compression library

$ vcpkg integrate install

$ cmake -B build -S . -DKQ_DATADIR="$PWD" -DCMAKE_TOOLCHAIN_FILE="$(realpath "$PWD/../vcpkg/scripts/buildsystems/vcpkg.cmake" )"
```
After I rebuilt the project in VS2022, I'm able to hear sound and music. Do you know whether the `nativemidi` feature should be included? I can add that to the build instructions.

**Comment by pedro-w** [comment]
Baffling. Anyway good that it's finally working. My understanding is that you shouldn't need nativemidi because none of the music is MIDI - only way is to blow out your `vcpkg/` again and re-install!

It may be worth looking at vcpkg manifest mode - this seems to be able to handle the automatic installation of dependencies
https://vcpkg.io/en/docs/users/manifests.html
https://vcpkg.io/en/docs/examples/manifest-mode-cmake.html

**Comment by OnlineCop** [comment]
That's true. I'll write up a new issue and probably reference z9484's [EngineRework](https://github.com/OnlineCop/kq-fork/wiki/EngineRework#building-on-windows-with-new-sdl-branch-on-road_to_10) wiki page, since it appears that there's a good manifest there as a starting point.

**Pull request merged**
